name: Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  issues-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}

      - run: |
          issue_tittle="$ISSUE_TITLE"
          if [[ "$issue_tittle" == *"bug"* ]]; then
            echo "Issue is about a bug!"
          else
            echo "Issue is not about a bug"
          fi
